import { isUtf8 } from "node:buffer";
import clipboardEvent from "clipboard-event";
import type { ClipboardBookmark } from "electron";
import electron, { ClipboardItem } from "electron";
import { enrichClipItem } from "./enrichClipItem";
import { Mime } from "./Mime";
import { storage } from "./storage";
import type {
    ClipBookmark,
    ClipEntry,
    ClipFormat,
    ClipItem,
    ClipItemType,
} from "./types/types";
import { getNextClipItemId } from "./util/clipItemId";
import {
    convertBase64ToBlob,
    convertBufferToBase64,
    convertBufferToUtf8,
} from "./util/converting";
import { showErrorNotification } from "./util/notifications";
import { toMarkdownImageLink } from "./util/transformations";

// Clipboards containing any of these formats should not be saved
const ignoreFormats = new Set(
    [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.source",
        "ExcludeClipboardContentFromMonitorProcessing",
    ].map(getElectronFormat),
);

function getElectronFormat(format: string): string {
    return `electron application/osclipboard;format="${format}"`;
}

const EXCLUDED = Symbol("excluded");

async function read(
    created: number,
): Promise<ClipItem | null | typeof EXCLUDED> {
    const entries = await electron.clipboard.read();

    const resEntries: ClipEntry[] = [];
    let resType: ClipItemType = "text";

    for (const entry of entries) {
        const resFormats: ClipFormat[] = [];
        let bookmark: ClipBookmark | undefined = undefined;

        for (const type of entry.types) {
            // If the clipboard contains ignored formats, skip processing this clipboard
            if (ignoreFormats.has(type)) {
                return EXCLUDED;
            }

            const data = await entry.getType(type);

            if (data instanceof Blob) {
                const buf = await data.arrayBuffer();

                if (type.startsWith(Mime.textPrefix) && isUtf8(buf)) {
                    resFormats.push({
                        mime: type,
                        encoding: "utf8",
                        data: convertBufferToUtf8(buf),
                    });
                    continue;
                }

                resFormats.push({
                    mime: type,
                    encoding: "base64",
                    data: convertBufferToBase64(buf),
                });

                if (type.startsWith(Mime.imagePrefix)) {
                    resType = "image";
                }
            }
            // If the data is not a Blob, it is assumed to be a bookmark
            else {
                bookmark = { mime: type, title: data.title, url: data.url };
            }
        }

        if (resFormats.length > 0 || bookmark != null) {
            resEntries.push({ formats: resFormats, bookmark });
        }
    }

    if (resEntries.length === 0) {
        return null;
    }

    const id = getNextClipItemId(created);

    return enrichClipItem({
        version: 1,
        id,
        created,
        type: resType,
        name: undefined,
        list: undefined,
        entries: resEntries,
    });
}

async function write(items: ClipItem[]) {
    if (items.length === 1) {
        await writeItem(items[0]);
    } else {
        await writeItems(items);
    }
}

async function writeItems(items: ClipItem[]) {
    const texts: string[] = [];
    for (const item of items) {
        const { type } = item;
        switch (type) {
            case "text":
                texts.push(item.text);
                break;
            case "image": {
                const name = item.name ?? item.alt ?? "IMAGE";
                if (item.src != null) {
                    texts.push(toMarkdownImageLink(name, item.src));
                } else {
                    texts.push(name);
                }
                break;
            }
            default: {
                const _exhaustiveCheck: never = type;
                throw new Error("Unsupported item type");
            }
        }
    }
    await electron.clipboard.writeText(texts.join("\n"));
}

async function writeItem(item: ClipItem) {
    const entries: ClipboardItem[] = [];

    for (const entry of item.entries) {
        const formatMap: Record<string, string | Blob | ClipboardBookmark> = {};
        for (const { mime, encoding, data } of entry.formats) {
            formatMap[mime] =
                encoding === "utf8" ? data : convertBase64ToBlob(data, mime);
        }
        if (entry.bookmark != null) {
            const { mime, title, url } = entry.bookmark;
            formatMap[mime] = { title, url };
        }
        entries.push(new ClipboardItem(formatMap));
    }

    await electron.clipboard.write(entries);
}

function onChange(
    listener: (item: ClipItem, lastExcludedAt: number | undefined) => void,
) {
    clipboardEvent.startListening();

    let lastExcludedAt: number | undefined;
    let processingQueue = Promise.resolve();
    let clipboardGeneration = 0;

    clipboardEvent.on("change", () => {
        const generation = ++clipboardGeneration;

        if (storage.getConfig().paused) {
            return;
        }

        const created = Date.now();

        const result = read(created)
            .then((item) =>
                // If the read item was excluded due to ignored formats, keep it as EXCLUDED.
                // Otherwise, only consider the item if it is from the latest clipboard generation.
                item === EXCLUDED || generation === clipboardGeneration
                    ? item
                    : null,
            )
            .catch((error: unknown) => {
                showErrorNotification("Failed to read clipboard", error);
                return null;
            });

        processingQueue = processingQueue
            .then(async () => {
                const item = await result;

                if (item === EXCLUDED) {
                    lastExcludedAt = created;
                } else if (item != null) {
                    const excludedAt = lastExcludedAt;
                    lastExcludedAt = undefined;
                    listener(item, excludedAt);
                }
            })
            .catch((error: unknown) => {
                showErrorNotification(
                    "Failed to process clipboard change",
                    error,
                );
            });
    });
}

export const clipboard = {
    write,
    onChange,
};
