name: Create release

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Read version from package.json
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag v${{ steps.get-version.outputs.version }}
          git push origin v${{ steps.get-version.outputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.get-version.outputs.version }}
          tag_name: v${{ steps.get-version.outputs.version }}
          body: Release for version ${{ steps.get-version.outputs.version }}
          target_commitish: ${{ github.event.workflow_run.head_sha }}

  upload-assets:
    name: Upload assets
    needs: create-release
    if: ${{ needs.create-release.result == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm --color ci

      - name: Package artifact
        run: npm --color run package

      - name: Compress artifact (Windows)
        shell: pwsh
        run: >
          Compress-Archive -Path 'dist/*'
          -DestinationPath "Clippy-${{ needs.create-release.outputs.version }}-${{ runner.os }}.zip"
        if: runner.os == 'Windows'

      - name: Compress artifact (macOS and Linux)
        shell: bash
        run: |
          cd dist
          zip -r "../Clippy-${{ needs.create-release.outputs.version }}-${{ runner.os }}.zip" *
        if: runner.os != 'Windows'

      - name: Upload release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh release upload
          "v${{ needs.create-release.outputs.version }}"
          "Clippy-${{ needs.create-release.outputs.version }}-${{ runner.os }}.zip"
