name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create Git tag
        id: create_tag
        run: |
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.version }}"
          release_name: "${{ env.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # deploy:
  #   name: Deploy
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version-file: .nvmrc
  #     - run: npm --color install
  #     - run: npm --color run compile
  #     - run: xvfb-run -a npm --color run test:ci
  #       if: runner.os == 'Linux'
  #     - run: npm --color run test:ci
  #       if: runner.os != 'Linux'
